package com.whereismymoney.WhereIsMyMoney.Repositories;

import com.whereismymoney.WhereIsMyMoney.Entities.Record;
import com.whereismymoney.WhereIsMyMoney.Entities.User;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface RecordRepo extends JpaRepository<Record, Long> {

    List<Record> findByUser(User currentUser);
    // Basic CRUD methods are automatically generated by Spring Data JPA
}


