
spring.application.name=${APP_NAME}
server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}


spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO}
spring.main.lazy-initialization=${LAZY}


spring.ai.google.genai.api-key=${GEMINI_AI_KEY}
spring.ai.google.genai.chat.model=${AI_MODEL}

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SPRING_SENDGRID_API-KEY}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true










# spring.application.name=WhereIsMyMoney
# server.port=9090

# spring.datasource.url=jdbc:mysql://localhost:3306/whereismymoney_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# # spring.jpa.show-sql=true
# # spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# # logging.level.root=INFO
# # logging.level.org.springframework.web=INFO
# # logging.level.org.hibernate.SQL=DEBUG

# spring.main.lazy-initialization=true

# spring.ai.google.genai.api-key=***
# spring.ai.google.genai.chat.model=***


# # SMTP Connection Server Parameters
# spring.mail.host=smtp.sendgrid.net
# spring.mail.port=587
# spring.mail.username=apikey
# spring.mail.password=***

# # Protocol Security Options
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true



# 1. Enable the file watcher mechanism
# spring.devtools.restart.enabled=true

# # 2. Quiet Period: Wait 5 seconds after the last file modification before restarting
# spring.devtools.restart.poll-interval=2000ms

# # 3. Quiet Period: Ensure no additional file modifications happen for 4 seconds
# spring.devtools.restart.quiet-period=1000ms
