
spring.application.name=${APP_NAME}
server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}


spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL}
spring.jpa.properties.hibernate.dialect=${DB_DIALECT}

logging.level.root=${LOG_LEVEL_ROOT}
logging.level.org.springframework.web=${LOG_LEVEL_SPRING}
logging.level.org.hibernate.SQL=${LOG_LEVEL_HIBERNATE}


